### ISSUE TITLE
Block action complete until Percy test completes and publish the results

### ISSUE THREAD

**Issue by dvoytenko** [percy/snapshot-action#10]
We've included Percy run as following:

```
      - name: Upload Percy snapshots
        uses: percy/snapshot-action@v0.1.1
        with:
          build-directory: '.build/site'
          flags: '--config=percy.config.yml'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```

I can see this action runs, but it always completes successfully with the following record:

```
[percy] finalized build #308: https://percy.io/Web-Stories-for-WordPress/web-stories-wp/builds/5667462
```

Is there a way to make the action to block until the Percy test run actually completes and report the test results as a pull request status pending approval/disapproval inside Percy?
