### ISSUE TITLE
specify specific ruby and gem versions

### ISSUE THREAD

**Issue by artivilla** [percy/snapshot-action#15]
would like to stick to these specific versions so I this configuration:
```
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Install
        run: gem install bundler:2.1.4 && bundle install
      - name: Build
        run: bundle exec jekyll build
      - name: Percy Snapshots
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "_site"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
but github actions doesn't seem to like this:
`Error: Version 2.6.3 not found`

does setup-ruby not support these versions?
